### ISSUE TITLE
error: attribute android:forceDarkAllowed not found

### ISSUE THREAD

**Issue by DwayneZhang** [android/android-DarkTheme#2]
i clone and run failed, this is error info:
Android resource linking failed
F:\OBJ\android-DarkTheme\Application\src\main\res\layout\fragment_preferences.xml:24: error: attribute android:forceDarkAllowed not found.
error: failed linking file resources.
what should i do?

**Comment by Mupceet** [comment]
I have the same problem

**Comment by Canivek** [comment]
Changing `compiledSdkVersion 28` to `compileSdkVersion 'android-Q'` should solve the issue. `android:forceDarkAllowed` attribute was only added in Android Q.  
Note: if you also change the `targetSdkVersion `to be 'Q', as Android Q is still in preview, you will only be able to run the app on an Android Q compatible device.

Unrelated to this issue, but it seems like you need to also update `'androidx.appcompat:appcompat:1.1.0-alpha04'` to `'androidx.appcompat:appcompat:1.1.0-alpha05'` or the theme switching doesn't work properly .

**Comment by DwayneZhang** [comment]
@Canivek According to what you said, I solved it, thanks
