### ISSUE TITLE
error: attribute android:forceDarkAllowed not found.

### ISSUE THREAD

**Issue by KunMinX** [android/android-DarkTheme#4]
I pulled this project from GitHub to run, But it seems something wrong of the new attribute 'forceDarkAllowed'.

Here is maven configurations of this project :
com.android.tools.build:gradle:3.4.0
distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
implementation 'com.google.android.material:material:1.1.0-alpha06'
implementation 'androidx.appcompat:appcompat:1.1.0-alpha05'
implementation 'androidx.constraintlayout:constraintlayout:2.0.0-beta1'
implementation 'androidx.preference:preference:1.1.0-alpha05'

Here is build out of Android Studio :
Android resource linking failed
D:\Projects\Android_UI_Solutions\Android_Skin\android-DarkTheme\Application\src\main\res\layout\fragment_preferences.xml:24: error: attribute android:forceDarkAllowed not found.
error: failed linking file resources.

**Comment by Canivek** [comment]
Duplicate of https://github.com/googlesamples/android-DarkTheme/issues/2. A solution is given here https://github.com/googlesamples/android-DarkTheme/issues/2#issuecomment-491553873.
I just made a PR to fix it.

**Comment by KunMinX** [comment]
@Canivek  Thanks a lot, it works.
